pipeline {
    agent any
    environment {
        rcred = 'dockerhub'
        rname = 'survey-app-img'
    }
    

    stages {
         stage('Checkout'){
            agent any
            steps{
                checkout scm
            }
        }
        stage('build') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: rcred, usernameVariable: 'ACR_USER', passwordVariable: 'ACR_PASSWORD')]) {
                      sh "docker login --username ${ACR_USER} --password ${ACR_PASSWORD}"
        sh "docker build -t survey-app-img:$BUILD_ID DevOps-Pipeline-Python/Python"
                        sh "docker tag survey-app-img:$BUILD_ID survey-app-img:$BUILD_ID"
        sh "docker push bouchra445/survey-app-img:$BUILD_ID "
                    }
                }
            }
        }
        stage('logout'){
            agent any
            steps {
                sh 'docker logout'
            }
        }
    }
}
