pipeline{
  agent any
  environment{
    rcred='dockerhub'
    rname='survey-app-img'
  }
  stages{
    stage('build'){
      steps{
        script{
                      withCredentials([usernamePassword(credentialsId: rcred, usernameVariable: 'ACR_USER', passwordVariable: 'ACR_PASSWORD')]) {
                        sh "az acr login --username ${ACR_USER} --password ${ACR_PASSWORD} --name ${rname}"
                        sh 'docker bouchra445/survey-app-img/:latest DevOps-Pipeline-Python/Python'
                        sh "docker push bouchra445/survey-app-img/:latest"
   

                           

                    }
           
        }
      }
    }
  }
}
  
