version: "3.8" #version mt3 syntaxe eli mktoub beha file
services: #services eli bch n3mlou run fi conteneur 
  app:
    build: .  #bch y3ml build l dockerfile eli mawjoud fi current directory w y3mli image 
    command: python3 manage.py runserver 0.0.0.0:8000 #lena bch n3ml run l conteneur b port 8000
    ports:
      - "4000:8000"
    volumes:
      - .:/usr/src/app
#      - sqlite_data:/usr/src/app/db
#    environment:
#      - DATABASE_URL=sqlite:////usr/src/app/db/data.sqlite3

#volumes:
#  sqlite_data:
