apiVersion: apps/v1 
kind: Deployment #hedha naw3 ressource
metadata:
  name: survey-app-deploy 
  namespace: python-app
  labels:
    app: survey-app
spec:
  selector:
    matchLabels:
      app: survey-app
  replicas: 2
  template:
    metadata:
      labels:
        app: survey-app
    spec:
      containers:
      - name: survey-app
        image: bouchra445/survey-app-img:83:82:81:80:79:78:77:76:75:74:73:71:70:69:68:67:66:65:64:63:62:61:60:59:58:57:56:55:54:53:52:51:50:49:48:47:46:45:44:43:42:41:40:39:38:37:35
        ports:
        - containerPort: 8000